version: '3'
services:
  scrapper-client:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: scrapper-client
    stdin_open: true
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - scrapper-server
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000

  scrapper-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: scrapper-server
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    stdin_open: true
    links:
      - mongodb
    volumes:
      - ./server/:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  node_modules:
  mongo-data:
    driver: local